In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define voc size 
voc_size = 10000

In [5]:
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[6945, 6463, 5103, 6306],
 [6945, 6463, 5103, 4941],
 [6945, 8762, 5103, 2489],
 [8043, 3629, 4147, 8782, 8077],
 [8043, 3629, 4147, 8782, 6743],
 [5912, 6945, 5301, 5103, 9795],
 [8396, 547, 7150, 8782]]

In [16]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding, Input
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 

In [17]:
sent_length = 8 
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6945 6463 5103 6306]
 [   0    0    0    0 6945 6463 5103 4941]
 [   0    0    0    0 6945 8762 5103 2489]
 [   0    0    0 8043 3629 4147 8782 8077]
 [   0    0    0 8043 3629 4147 8782 6743]
 [   0    0    0 5912 6945 5301 5103 9795]
 [   0    0    0    0 8396  547 7150 8782]]


In [18]:
## feature representation
dim = 10

In [19]:
model = Sequential(
    [
        Input(shape=(sent_length,)),
        Embedding(input_dim=voc_size, output_dim=dim),
    ]
)

In [20]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


array([[[-0.03151083, -0.03382327,  0.04041339, -0.02297487,
          0.00348127, -0.03884929,  0.03329027,  0.04877354,
         -0.03969048, -0.00181432],
        [-0.03151083, -0.03382327,  0.04041339, -0.02297487,
          0.00348127, -0.03884929,  0.03329027,  0.04877354,
         -0.03969048, -0.00181432],
        [-0.03151083, -0.03382327,  0.04041339, -0.02297487,
          0.00348127, -0.03884929,  0.03329027,  0.04877354,
         -0.03969048, -0.00181432],
        [-0.03151083, -0.03382327,  0.04041339, -0.02297487,
          0.00348127, -0.03884929,  0.03329027,  0.04877354,
         -0.03969048, -0.00181432],
        [ 0.03619939,  0.00814115, -0.04502463,  0.0464507 ,
         -0.03960811, -0.02412565,  0.0072917 ,  0.04879597,
         -0.02494988, -0.01407314],
        [ 0.02088031, -0.00253428, -0.00062313,  0.04251726,
         -0.02078341, -0.0316522 , -0.02741064,  0.01989826,
          0.0078698 ,  0.04009299],
        [ 0.02541771, -0.028819  ,  0.00928418, -0.0